server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password
    ssl:
      enabled: false
    exchange:
      producer: ex.producer.rmqsbd
    routing-key:
      producer: rk.producer.rmqsbd
    dead-letter:
      producer: dl.producer.rmqsbd